name: node CI
on:
  push:
    branches: [master]
job:
  build:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm test || echo "Tests failed, but continuing to deploy"
      - run: echo "build succesfull"
